<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAx68d92\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAx68d92/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAx68d92.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAx68d92\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAx68d92\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ax68d92',
    'container.build_id' => 'd2496033',
    'container.build_time' => 1585731147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAx68d92');
