<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCmrWsQQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCmrWsQQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCmrWsQQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCmrWsQQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCmrWsQQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CmrWsQQ',
    'container.build_id' => '6cc468ef',
    'container.build_time' => 1585080548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCmrWsQQ');
