<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEu895Sp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEu895Sp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEu895Sp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEu895Sp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEu895Sp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eu895Sp',
    'container.build_id' => '71522427',
    'container.build_time' => 1586133731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEu895Sp');
